# Generated by Django 5.2.1 on 2025-05-07 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Название категории (макс. 30 символов)', max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_private', models.BooleanField(default=False, help_text='Видна только владельцу?')),
                ('description', models.TextField(blank=True, help_text='Описание (необязательно)', null=True)),
                ('owner', models.ForeignKey(help_text='Владелец категории', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
    ]
